import Nav from '@/components/Nav';
import { ProfileForm } from '@/components/UserForm';
import { Button } from '@/components/ui/button';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SHIT',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="p-24">
      <Nav />
      <section className="py-12 flex flex-col gap-8 items-center text-center">
        <h1 className="text-4xl">Shadcdn is Awesome</h1>
        <p className="text-2xl text-muted-foreground">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio,
          quod culpa!{' '}
          <a className="underline decoration-sky-500">My Company, In.</a>{' '}
          Accusantium incidunt tempora nesciunt?
        </p>
      </section>
      <div className="flex gap-6 items-center justify-center">
        <Button variant={'secondary'}>Learn More</Button>
        <Button>Enroll Now</Button>
      </div>
      <div>
        <ProfileForm />
      </div>
    </main>
  );
}
